### ISSUE TITLE
Multiple Upload File: icon is not displayed

### ISSUE THREAD

**Issue by Kostelano** [PhocaCz/PhocaDownload#13]
Good afternoon! Small problem - the icon is not displayed in the field for multi-uploading files.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/97789351-6feacc80-1bc8-11eb-8757-1affc5f3c307.png)

Mozilla
Phoca Download 3.2.1

**Comment by PhocaCz** [comment]
Hi, thank you for the info, it is rendered by Glyphicons which are not loaded. Will be fixed in next version.

**Comment by PhocaCz** [comment]
Change in: media\com_phocadownload\css\administrator\phocadownload.css

FROM:
```css

ul.plupload_filelist li .plupload_file_name:before {
	font-family: 'Glyphicons Halflings';
	color: #d0d0d0;
    content: "\e022";
	float: left;
	margin: 0px 5px 5px 0px;
	padding-bottom: 2px;
}
...
li.plupload_droptext:before {
	font-family: 'Glyphicons Halflings';
	color: #d0d0d0;
    content: "\e022 ";
	font-size: 200%;
	text-align: center;
	margin: 0px auto;
	/*display: block-inline;*/
	float:none;
}
```
TO:

```css
ul.plupload_filelist li .plupload_file_name:before {
	font-family: 'JoomlaFont' !important;
	color: #d0d0d0;
    content: "\13b2a";
	float: left;
	margin: 0px 5px 5px 0px;
	padding-bottom: 2px;
}
...
li.plupload_droptext:before {
	font-family: 'JoomlaFont' !important;
	color: #d0d0d0;
    content: "\13b2a";
	font-size: 200%;
	text-align: center;
	margin: 0px auto;
	/*display: block-inline;*/
	float:none;
}
```

![img](https://i.imgur.com/4q0iRwv.png)
